const actionTypes = {
  GET_TOOLS: "GET_TOOLS",
  SEARCH_TOOLS: "SEARCH_TOOLS",
  SEARCH_TAGS: "SEARCH_BY_TAG",
  TOGGLE_BY_TAG: "TOGGLE_BY_TAG",
  UPDATE_SEARCH_TERM: "UPDATE_SEARCH_TERM",
  FETCH_TOOLS_SUCCEED: "FETCH_TOOLS_SUCCEED",
  FETCH_TOOLS_FAILED: "FETCH_TOOLS_FAILED",
  DELETE_TOOL: "DELETE_TOOL",
  DELETE_TOOL_SUCCEED: "DELETE_TOOL_SUCCEED",
  DELETE_TOOL_FAILED: "DELETE_TOOL_FAILED"
};

export { actionTypes };
